name: gohealth
description: Modern Flutter multiplatform application

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.2.0

  # State Management
  provider: ^6.1.1

  # Network
  dio: ^5.4.0

  # Authentication

  # Local Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  # UI
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  fl_chart: ^1.0.0

  # Supabase
  supabase_flutter: ^2.5.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.1.1
  flutter_local_notifications: ^19.2.1

  # Utils
  intl: ^0.20.2
  logger: ^2.0.2+1
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
