name: gohealth
description: Modern Flutter multiplatform application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^12.1.3

  # State Management
  flutter_riverpod: ^2.4.9

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # UI
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0


  fl_chart: ^1.0.0
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  

